# Generated by Django 5.1.5 on 2025-02-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField(unique=True)),
                ('atomic_mass', models.FloatField()),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('period', models.IntegerField()),
            ],
        ),
    ]
