# Generated by Django 5.1.5 on 2025-02-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='group',
        ),
        migrations.RemoveField(
            model_name='element',
            name='period',
        ),
        migrations.AddField(
            model_name='element',
            name='boiling_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.CharField(default='filled', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='melting_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
