# Generated by Django 5.1.5 on 2025-02-06 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0002_remove_element_group_remove_element_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("chemical_formula", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("bond_type", models.CharField(max_length=50)),
                ("properties", models.TextField()),
                ("uses", models.TextField()),
                ("status", models.CharField(max_length=20)),
                ("discovery_date", models.DateField()),
                ("source", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CompoundElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.compound"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest.element"
                    ),
                ),
            ],
        ),
    ]
