# Generated by Django 5.1.5 on 2025-02-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0003_compound_compoundelement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="status",
            field=models.CharField(max_length=30),
        ),
    ]
