# Generated by Django 5.1.5 on 2025-02-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0004_alter_compound_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="discovery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
