# Generated by Django 5.1.5 on 2025-03-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_compound_discovery_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='discovery_by',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
