# Generated by Django 5.1.5 on 2025-07-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_compound_discovery_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='block',
            field=models.CharField(choices=[('s', 'S Block'), ('p', 'P Block'), ('d', 'D Block'), ('f', 'F Block')], default='s', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='phase',
            field=models.CharField(choices=[('Solid', 'SOLID'), ('Liquid', 'LIQUID'), ('Gas', 'GAS'), ('Unknown', 'UNKNOWN'), ('Predicted Solid', 'PREDICTED SOLID'), ('Predicted Liquid', 'PREDICTED LIQUID'), ('Predicted Gas', 'PREDICTED GAS')], default='Unknown', max_length=17),
            preserve_default=False,
        ),
    ]
