# Generated by Django 5.1.5 on 2025-07-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_element_block_element_group_element_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='abundance_earth_crust',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='abundance_universe',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='appearance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='atomic_radius',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='covalent_radius',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='crystalStructure',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='discovery_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='discovery_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='electrical_conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='electron_affinity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='electron_configuration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='electron_egativity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='ionization_energy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='isotopes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='element',
            name='oxidation_state',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='element',
            name='specific_heat',
            field=models.FloatField(default=float(0.0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='thermal_conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='van_der_waals_radius',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
